import {
  AlertCircleIcon,
  Archive,
  Award,
  Bell,
  BookCheck,
  Building2,
  Calendar,
  CalendarClockIcon,
  CalendarIcon,
  CheckCircle,
  ChevronDown,
  Clock,
  DownloadIcon,
  FileStack,
  FileText,
  Languages,
  Loader2,
  LogIn,
  Paperclip,
  Pill,
  Plus,
  PowerOff,
  Settings,
  SlidersHorizontal,
  Stethoscope,
  Target,
  Timer,
  TrendingUp,
  User2Icon,
  UserPlus,
  X,
} from "lucide-react-native";
import { iconWithClassName } from "./IconWithClassName";

iconWithClassName(Loader2);
iconWithClassName(PowerOff);
iconWithClassName(User2Icon);
iconWithClassName(Settings);
iconWithClassName(SlidersHorizontal);
iconWithClassName(AlertCircleIcon);
iconWithClassName(Clock);
iconWithClassName(Timer);
iconWithClassName(Calendar);
iconWithClassName(TrendingUp);
iconWithClassName(Target);
iconWithClassName(Award);
iconWithClassName(DownloadIcon);
iconWithClassName(Plus);
iconWithClassName(CalendarClockIcon);
iconWithClassName(CalendarIcon);
iconWithClassName(Languages);
iconWithClassName(Bell);
iconWithClassName(CheckCircle);
iconWithClassName(X);
iconWithClassName(ChevronDown);
iconWithClassName(BookCheck);
iconWithClassName(Archive);
iconWithClassName(FileStack);
iconWithClassName(LogIn);
iconWithClassName(Stethoscope);
iconWithClassName(UserPlus);
iconWithClassName(Building2);
iconWithClassName(FileText);
iconWithClassName(Paperclip);
iconWithClassName(Pill);
export {
  AlertCircleIcon,
  Archive,
  Award,
  Bell,
  BookCheck,
  Building2,
  Calendar,
  CalendarClockIcon,
  CalendarIcon,
  CheckCircle,
  ChevronDown,
  Clock,
  DownloadIcon,
  FileStack,
  FileText,
  Languages,
  Loader2,
  LogIn,
  Paperclip,
  Pill,
  Plus,
  PowerOff,
  Settings,
  SlidersHorizontal,
  Stethoscope,
  Target,
  Timer,
  TrendingUp,
  User2Icon,
  UserPlus,
  X,
};
